AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Serverless app that will recieve API call to initiate and fetch a number
  from  A DynamoDB table, update the number +1, and post new number to webpage.

  '
Globals:
  Function:
    Timeout: 60
Resources:
  visitCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role:
        Fn::GetAtt:
        - visitCountFunctionIAMRole
        - Arn
      FunctionName: visitCountFunction
      CodeUri: s3://jakobondrey-visitor-count-lambda/76e07787e122ef0f25a2187900c6e501
      Handler: app.get_update_visit_counter
      Runtime: python3.8
      Events:
        TestAppAPI:
          Type: Api
          Properties:
            Path: /Prod
            Method: get
  visitCountFunctionIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Principal:
            Service:
            - lambda.amazonaws.com
          Effect: Allow
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: VisitorCountLambdaPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*
          - Effect: Allow
            Action:
            - dynamodb:UpdateItem
            Resource:
            - Fn::GetAtt:
              - DynamoDBTable
              - Arn
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jakobondrey_visitor_count
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: site_url
        AttributeType: S
      KeySchema:
      - AttributeName: site_url
        KeyType: HASH
Outputs:
  CountAppAPI:
    Description: API Gateway endpoint URL for Visitor Count function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Production/visitCount/
  visitCountFunction:
    Description: Visit Counter Function ARN
    Value:
      Fn::GetAtt:
      - visitCountFunction
      - Arn
