AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Serverless app that will recieve API call to initiate and fetch a number from 
    A DynamoDB table, update the number +1, and post new number to webpage.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60 

Resources:
  visitCountFunction: # This needs to match the values in Outputs. Both the heading and !GetAtt .Arn
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment: 
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      #Role: !GetAtt visitCountFunctionIAMRole.Arn
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt DynamoDBTable.Arn
      CodeUri: app/ # This is the file path where your function file is located
      Handler: app.get_update_visit_counter # This is the function File.function
      Runtime: python3.8 # This is the language that the file is written in
      Events:
        TestAppAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /Prod # this is the path when you test the API locally
            Method: get
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: site_url
          AttributeType: S
      KeySchema: 
        - AttributeName: site_url
          KeyType: HASH

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CountAppAPI:
    Description: "API Gateway endpoint URL for Visitor Count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Production/visitCount/" # this will be the url to access once on AWS. You can change the /Prod/test-app/ part
  visitCountFunction:
    Description: "Visit Counter Function ARN"
    Value: !GetAtt visitCountFunction.Arn